# Generated by Django 3.0.2 on 2020-02-13 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20200213_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadocivil',
            old_name='estadoCivil',
            new_name='estado_civil',
        ),
    ]
